# Name of workflow
name: From develop to main

# Trigger workflow on all pull requests
on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - develop

# Jobs to carry out
jobs:
  test:
    # Operating system to run job on
    runs-on: ubuntu-latest

    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      # Install dependencies
      - name: Install Deps
        run: npm install
        
      # Build Application
      - name: Build application
        run: npm run build

      # Run the cypress tests 
      - name: Start server and run the npm test
        run: npx start-server-and-test "npm run start" http://localhost:3001 "npm run test"
        env:
          CI: true
          MONGODB_URI: 'mongodb+srv://fabiansm:Elreforma11@cluster0.bjzel.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'